<template>
  <div class="about">
    <div class="container">
          <section class="section">
            <nav class="breadcrumb" aria-label="breadcrumbs">
              <ul>
                  <li>
                    <router-link to="/">
                        Bet UFC
                    </router-link>
                  </li>
                  <li class="is-active">
                      <a>About</a>
                  </li>
              </ul>
            </nav>
            <div class="content">
              <h1>UFC Prediction Engine</h1>
              <p> This application aims to provide a profitable betting approach by removing human bias and relying only on statical evidence.</p>
              <h2> Trust the System </h2>

              <p> The value proposition for this algorithm is two pronged: </p>
              <ol>
                <li> Limit downside through the removal of personal bias </li>
                <li> Identify areas of opportunity spawned from emotional and non-quantitative UFC bettors </li>
              </ol>

              <p> 
                This algorithm is trained, back-tested, and cross-validated to reach an optimal set of rules which maximize long term results through the identification of <strong> value </strong> picks.  At the end of the night, its not how many fights you pick correctly, its how much money did you win.  Betting on heavy favorites is tempting, but not a sustainable long term approach.  Instead, a progressive betting approach seeks out value and wagers corresponding to the expected ROI.  
              </p>

              <h2> Identification of Value and Wager Calculation</h2>
              <p>
                The issue many face is difficulty in conceptualizing probabilities and reflecting changes in decision making: we react the same way to 54% as 56%, both are seen as "slightly above half".  But with a standard vig, that 2% is the difference between long term profit and loss.  This difficulty only compounds as odds increase.  To a person, -285 and -310 are roughly equivalent.  The goal of this application is to both remove this flaw from our bets as well as capitalize on its existance.
              </p>
              <p>
                For each bout which meets a series of optimized thresholds and criteria, an expected win probability for each fighter is generated by the core model.  These odds are then compared to the implied probability of the average Vegas money line.  The difference between these values is then fed through a top-level algorithm which filters non-advantagous bets and determines the optimal wager amount.
              </p>
              <p>
                This model does <strong>not</strong> use a standard bet, proportioned across candidates.  It evaludates each bet independently and only considers expected ROI.  This means that some fights may have very low action or even no bets made.  
              </p>    
              <p>
                The model's range for wagers is $0 - $200.  It is recommended to either use the same wagers provided, or to scale each wager by a common factor.  Additionally, the wagers are all based on average Vegas odds.  Your book may be slightly different, and our team is working on a conversion feature. 
              </p>

              <h2> Calculation of Win Probability </h2>
              <p> 
                The main driver for identifying value bets is our win probability algorithm.  Every stat feeds into a set of 8 characteristics for a fighter, updated through an pseudo-ELO approach.  There are 4 base values:
              </p>
              <ol>
                <li> <strong>Striking Offense</strong>: ability to generate striking output consistent with a knockout</li>
                <li> <strong>Striking Defense</strong>: ability to avoid striking consistent with a knockout </li>
                <li> <strong>Grappling Offense</strong>: ability to generate grappling output consistent with a submission</li>
                <li> <strong>Grappling Defense</strong>: ability to avoid grappling output consistent with a submission </li>
              </ol>
              <p>
                And 4 "multiplier" values:
              </p>
              <ol>
                <li> <strong>KO Power</strong>: ability to generate knockouts from striking output not consistent with a knockout  </li>
                <li> <strong>Chin</strong>: ability to withstand striking output consistent with a knockout </li>
                <li> <strong>Submission</strong>: ability to generate submissions from grappling output not consistent with a submission  </li>
                <li> <strong>Evasiveness</strong>: ability to withstand grappling output consistent with a submission </li>
              </ol>

              <h2>
                Technical Specs
              </h2>
                
              <p>
                The platform is a full-stack distributed architecture, utilizing Vue.js front end, python-flask and java spring-boot API layers, and a Postgresql DB backend.  The environment is hosted through IBM Cloud using Cloud Foundry.
              </p>
        
            </div>
          </section>
    </div>
  </div>
</template>
